wake_word:
  method: porcupine
  porcupine_access_key: "9hh0EnNx9fMqzipUHY38zQLL7GWC3zDGSs1ipIEbL1bhvcIheNY/xw=="
  keyword_path: "keywords/Dollar-jack_en_mac_v3_0_0.ppn"

stt:
  model: small

intent:
  use_fuzzy: true
  use_llm_fallback: false

tts:
  method: pyttsx3
  rate: 150
  volume: 0.8
  coqui_model: tts_models/en/ljspeech/tacotron2-DDC

audio:
  sample_rate: 16000
  record_duration: 3
